option(ENABLE_CACHE "Enable cache if available" ON)
if(NOT ENABLE_CACHE)
  return()
endif()

set(CACHE_OPTION
    "ccache"
    CACHE STRING "Compiler cache to be used")
set(CACHE_OPTION_VALUES "ccache" "sccache")
set_property(CACHE CACHE_OPTION PROPERTY STRINGS ${CACHE_OPTION_VALUES})
list(
  FIND
  CACHE_OPTION_VALUES
  ${CACHE_OPTION}
  CACHE_OPTION_INDEX)

if(${CACHE_OPTION_INDEX} EQUAL -1)
  message(
    STATUS
      "Using custom compiler cache system: '${CACHE_OPTION}', explicitly supported entries are ${CACHE_OPTION_VALUES}")
endif()

find_program(CACHE_BINARY ${CACHE_OPTION})
if(NOT CACHE_BINARY)
  message(WARNING "${CACHE_OPTION} is enabled but was not found. Not using it")
  return()
endif()

# ccache reads its settings from the environment or a config file, neither of which a compiler launcher can set on its
# own. A generated wrapper carries the repository's ccache.conf into every compile without anyone having to export
# anything, and keeps developer and CI settings identical.
if(CACHE_OPTION STREQUAL "ccache" AND EXISTS "${CMAKE_CURRENT_LIST_DIR}/../devtools/ccache.conf")
  set(_ccache_launcher "${CMAKE_BINARY_DIR}/ccache-launcher.sh")
  file(
    WRITE "${_ccache_launcher}"
    "#!/bin/sh\n"
    "# generated by cmake/Cache.cmake — do not edit\n"
    "export CCACHE_CONFIGPATH='${CMAKE_SOURCE_DIR}/devtools/ccache.conf'\n"
    # base_dir must be an absolute path that contains both sources and build trees for rewriting to take effect
    "export CCACHE_BASEDIR='${CMAKE_SOURCE_DIR}'\n"
    "exec ${CACHE_BINARY} \"$@\"\n")
  file(
    CHMOD
    "${_ccache_launcher}"
    PERMISSIONS
    OWNER_READ
    OWNER_WRITE
    OWNER_EXECUTE
    GROUP_READ
    GROUP_EXECUTE
    WORLD_READ
    WORLD_EXECUTE)
  set(CMAKE_C_COMPILER_LAUNCHER "${_ccache_launcher}")
  set(CMAKE_CXX_COMPILER_LAUNCHER "${_ccache_launcher}")
  message(STATUS "${CACHE_OPTION} enabled with the repository configuration (${CMAKE_SOURCE_DIR}/devtools/ccache.conf)")
else()
  set(CMAKE_C_COMPILER_LAUNCHER ${CACHE_BINARY})
  set(CMAKE_CXX_COMPILER_LAUNCHER ${CACHE_BINARY})
  message(STATUS "${CACHE_OPTION} found and enabled")
endif()
